language: R # https://github.com/jgm/pandoc/wiki/Using-pandoc-in-Travis-CI
sudo: false
script: true
# pandoc_version: 2.1.2 # default is 2.2
addons:
  apt:
    packages:
      - texlive-xetex
before_install:
  - shopt -s expand_aliases
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi
  - tlmgr install xcolor mdframed needspace unicode-math filehook lm-math # https://github.com/travis-ci/travis-ci/issues/7863
install:
  - pip install pygments
  - pip install mkdocs
  - pip install pymdown-extensions
  - pip install mkdocs-pandoc
  - pip install pandoc-latex-admonition
  - pip install git+https://github.com/o2r-project/mkdocs-combine.git
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./.site_build.sh ; fi
  - make travis_pdf travis_md
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./.site_deploy.sh ; fi
env:
  global:
    - PYENV_VERSION: "3.6.3"
    - SITE_URL: https://o2r.info/erc-spec
    - GH_USER_NAME: "Opening Reproducible Research"
    - GH_USER_EMAIL: openingrr@uni-muenster.de
    - GH_REF: github.com/o2r-project/erc-spec
    - secure: "Efeh2Pn31vxeNZHn+qWrGJfoD1FOoHDyrcAb9pRSbU5qDHKsUCxVukZEzpzgqRo0ZWciz4OCpNSDMErPxRIEYKdTAXDhTOwp9D1Fl6I6bNMDO0TSyKA7m3SMhrBfV6hyVaNnxkjEHYbYlfKTbl4TNJt966dHdesqqb4bffQUypAEnoV+L38KDRaobzwSmgFQQ6/h1VVpdE2KMMU8chwJ6uDyFiwmIPgOrIzijwCj+gYXmmefrVLsrjAbiWPsbbrFW6t0pWkwKy831M9UT9IgZHHgjpUNL4MbQoAMbn54erXe2g18nafIClVCEMCgFCkP3OiPyGe1ZgY/BN6j8TsUi6RYHF/TfNr6nbxvxeD90eOsiTd/Q3+hY0OB9WxdusiNkLrT0FoTFunyGxlo6ByL8HNxddL0Fg6s6Y4D9T8UWQ9FF9ymRS+geEPwxxkaigyUWmTwy6kanTxluYeowxkaKC5RAF4k4vHNf8Lyao/o6JZLI6tAO9Pd7TW1cVfcKJFx5N7ZUOlQcv3GB3YY/XHfjj74w2vvNlaS3IAatZUnzZPlXHc2Og31kzNm6hP34qOhpyT2a6cDtt2u5uc13OEGTx6P4zazNlLyG9Q5EDjqad4q+zAQlmfFakIMnP7AdBsmlO+Gjew/SGCv5v8WB5k5HQklnh1MCvNKrbmxxYzcPZc="
