site_name: ERC spec
site_author: "Daniel Nüst, Matthias Schutzeichel, Markus Konkol"
site_description: "Executable Research Compendium specification, user guide and developer guide"
pages:
  - Home: index.md
  - ERC:
    - Specification: spec/index.md
    - BagIt Extension: spec/bundle_bagit.md
    - R Extension: spec/r.md
    - Manipulation Extension: spec/man.md
  - User guide: user-guide/index.md
  - Developer guide: dev-guide/index.md
  - Glossary: glossary.md
theme:  cinder # material readthedocs # flatly
repo_url: https://github.com/o2r-project/erc-spec
repo_name: GitHub
edit_uri: blog/master/docs/
site_dir: site
extra_css: [erc.css]
