site_name: ERC spec
site_description: Executable Research Compendium Specification
site_author: "Daniel Nüst, Matthias Schutzeichel, Markus Konkol"
pages:
  - Home: index.md
  - ERC:
    - Specification: spec/index.md
    - BagIt Extension: spec/bagit.md
    - R Extension: spec/r.md
    - Manipulation Extension: spec/man.md
  - User guide: user-guide/index.md
  - Developer guide: dev-guide/index.md
  - Glossary: glossary.md
theme: cinder # readthedocs # flatly
site_author: o2r project
site_description: "Executable Research Compendium specification, user guide and developer guide"
site_dir: site
extra_css: [erc.css]
