site_name: "Executable Reserach Compendium (ERC) Specification"
site_author: "Daniel Nüst, Matthias Schutzeichel, Markus Konkol"
site_description: "Executable Research Compendium technical specification, user guides, developer guides, and support."
pages:
  - Home: index.md
  - ERC specification: spec/index.md
  - User guides:
    - Creation guide for authors: user-guide/creation.md
    - Examination guide for authors: user-guide/examination.md
    - ERC template for authors: user-guide/template.md
    - Minimal ERC examples: user-guide/minimal.md
    - ERC & OAIS: user-guide/oais.md
    - ERC as supplement: user-guide/erc_journal_supplement.md
    - Developer guide: dev-guide/index.md
  - Glossary: glossary.md
  - Support: support.md
theme:  readthedocs # cinder # material readthedocs # flatly
repo_url: https://github.com/o2r-project/erc-spec
repo_name: GitHub
edit_uri: tree/master/docs/
site_dir: site
extra_css: [erc.css]
markdown_extensions:
  - admonition
  - smarty
  - codehilite(guess_lang=False)
  - toc(permalink=true)
  #- pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.superfences # does not work with guess_lang=True